name: Migrate BI Publisher Reports

on:
  workflow_dispatch:  # Manual trigger from GitHub UI
  push:
    branches: [main]  # Also trigger on push to main

jobs:
  migrate:
    runs-on: ubuntu-latest

    env:
      # Source and Target BI Publisher URLs from GitHub Secrets
      SRC_BI_URL: ${{ secrets.SRC_BI_URL }}   # Source BI Publisher environment URL
      TGT_BI_URL: ${{ secrets.TGT_BI_URL }}   # Target BI Publisher environment URL
      BI_USER: ${{ secrets.BI_USER }}         # BI Publisher username (shared)
      BI_PASS: ${{ secrets.BI_PASS }}         # BI Publisher password or app password

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install zeep requests

      - name: Export Reports from SOURCE BI Publisher
        run: |
          mkdir -p exported_reports
          python3 scripts/export_bi_reports.py \
            --url "$SRC_BI_URL" \
            --username "$BI_USER" \
            --password "$BI_PASS" \

      - name: Upload Exported Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bi-reports
          path: exported_reports/

      - name: Import Reports to TARGET BI Publisher
        run: |
          python3 scripts/import_bi_reports.py \
            --url "$TGT_BI_URL" \
            --username "$BI_USER" \
            --password "$BI_PASS" \
