# .github/workflows/migrate_bi_reports.yml

name: Migrate BI Publisher Reports

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main]  # Trigger when code is pushed to main

jobs:
  migrate:
    runs-on: ubuntu-latest

    env:
      BI_USER: ${{ secrets.BI_USER }}
      BI_PASS: ${{ secrets.BI_PASS }}
      SRC_BI_URL: ${{ secrets.SRC_BI_URL }}
      TGT_BI_URL: ${{ secrets.TGT_BI_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install zeep

      - name: Export Reports from Source
        run: |
          python3 scripts/export_bi_reports.py \
            --url "$SRC_BI_URL" \
            --username "$BI_USER" \
            --password "$BI_PASS"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: bi-reports
          path: exported_reports/

      - name: Import Reports to Target
        run: |
          python3 scripts/import_bi_reports.py \
            --url "$TGT_BI_URL" \
            --username "$BI_USER" \
            --password "$BI_PASS"
