name: Migrate BI Publisher Reports

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  migrate:
    runs-on: ubuntu-latest

    env:
      SRC_BI_URL: ${{ secrets.SRC_BI_URL }}
      TGT_BI_URL: ${{ secrets.TGT_BI_URL }}
      BI_USER: ${{ secrets.BI_USER }}
      BI_PASS: ${{ secrets.BI_PASS }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install zeep requests

      - name: Export Reports from SOURCE BI Publisher
        run: |
          mkdir -p exported_reports
          python3 scripts/export_bi_reports.py --url "$SRC_BI_URL" --username "$BI_USER" --password "$BI_PASS"

      - name: Upload Exported Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bi-reports
          path: exported_reports/

      - name: Download Exported Reports Artifact
        uses: actions/download-artifact@v4
        with:
          name: bi-reports
          path: exported_reports/

      - name: Import Reports to TARGET BI Publisher
        run: |
          python3 scripts/import_bi_reports.py --url "$TGT_BI_URL" --username "$BI_USER" --password "$BI_PASS"
