name: Migrate BI Publisher Reports

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  migrate:
    runs-on: ubuntu-latest

    env:
      SRC_BI_URL: ${{ secrets.SRC_BI_URL }}
      TGT_BI_URL: ${{ secrets.TGT_BI_URL }}
      BI_USER: ${{ secrets.BI_USER }}
      BI_PASS: ${{ secrets.BI_PASS }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Export Reports from SOURCE BI Publisher (shell script)
        run: |
          mkdir -p exported_reports
          bash scripts/export_bi_reports.sh --url "$SRC_BI_URL" --username "$BI_USER" --password "$BI_PASS"

      - name: Upload Exported Reports as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: bi-reports
          path: exported_reports/

      - name: Import Reports to TARGET BI Publisher (Python script)
        run: |
          python3 scripts/import_bi_reports.sh --url "$TGT_BI_URL" --username "$BI_USER" --password "$BI_PASS"
