name: Migrate BI Publisher Reports

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  migrate:
    runs-on: ubuntu-latest

    env:
      SRC_BI_URL: ${{ secrets.SRC_BI_URL }}
      TGT_BI_URL: ${{ secrets.TGT_BI_URL }}
      BI_USER: ${{ secrets.BI_USER }}
      BI_PASS: ${{ secrets.BI_PASS }}

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install zeep requests

      - name: Export Reports from SOURCE BI Publisher
        run: |
          mkdir -p exported_reports
          python3 scripts/export_bi_reports.py \
            --url "$SRC_BI_URL" \
            --username "$BI_USER" \
            --password
